#! /bin/sh


if [[ $(hostname) == 'irunix' ]]; then
   bspc monitor DP-0 -d I II III IV V VI
   bspc monitor DVI-D-0 -d VII VIII 
elif [[ $(hostname) == 'chani' ]]; then
   bspc monitor -d I II III IV V VI VII VIII IX X
elif [[ $(hostname) == 'phryne' ]]; then
   bspc monitor -d I II III IV V VI VII VIII IX X
else
   bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config click_to_focus true

# Colors

bspc config normal_border_color    '#333841'
bspc config focused_border_color   '#eac58d'
bspc config active_border_color    '#ea4439'
bspc config presel_feedback_color  '#333841'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton &
numlockx off
~/opt/Telegram/Telegram -startintray &
sxhkd &
